<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>JapaneseArpasingPhonemizer</AssemblyName>
    <RootNamespace>JapaneseArpasingPhonemizer</RootNamespace>
    <DebugType>embedded</DebugType>
    <OpenUtauRoot Condition="'$(OpenUtauRoot)' == ''">../../OpenUtau</OpenUtauRoot>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="$(OpenUtauRoot)/OpenUtau.Core/OpenUtau.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="$(OpenUtauRoot)/OpenUtau.Plugin.Builtin/OpenUtau.Plugin.Builtin.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
