<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>JapaneseArpasingPhonemizer</AssemblyName>
    <RootNamespace>JapaneseArpasingPhonemizer</RootNamespace>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="OpenUtau.Core">
      <HintPath>../lib/OpenUtau.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OpenUtau.Plugin.Builtin">
      <HintPath>../lib/OpenUtau.Plugin.Builtin.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
