using System.Collections.Generic;

namespace JapaneseArpasingPhonemizer {
    internal static class KanaMap {
        public static readonly IReadOnlyDictionary<string, string[]> Entries =
            new Dictionary<string, string[]> {
            { "ぁ", new[] { "aa" } },
            { "あ", new[] { "aa" } },
            { "ぃ", new[] { "iy" } },
            { "い", new[] { "iy" } },
            { "ぅ", new[] { "uw" } },
            { "う", new[] { "uw" } },
            { "ぇ", new[] { "eh" } },
            { "え", new[] { "eh" } },
            { "ぉ", new[] { "ow" } },
            { "お", new[] { "ow" } },
            { "か", new[] { "k", "aa" } },
            { "が", new[] { "g", "aa" } },
            { "き", new[] { "k", "iy" } },
            { "ぎ", new[] { "g", "iy" } },
            { "く", new[] { "k", "uw" } },
            { "ぐ", new[] { "g", "uw" } },
            { "け", new[] { "k", "eh" } },
            { "げ", new[] { "g", "eh" } },
            { "こ", new[] { "k", "ow" } },
            { "ご", new[] { "g", "ow" } },
            { "さ", new[] { "s", "aa" } },
            { "ざ", new[] { "z", "aa" } },
            { "し", new[] { "sh", "iy" } },
            { "じ", new[] { "jh", "iy" } },
            { "す", new[] { "s", "uw" } },
            { "ず", new[] { "z", "uw" } },
            { "せ", new[] { "s", "eh" } },
            { "ぜ", new[] { "z", "eh" } },
            { "そ", new[] { "s", "ow" } },
            { "ぞ", new[] { "z", "ow" } },
            { "た", new[] { "t", "aa" } },
            { "だ", new[] { "d", "aa" } },
            { "ち", new[] { "ch", "iy" } },
            { "ぢ", new[] { "jh", "iy" } },
            { "つ", new[] { "t", "s", "uw" } },
            { "づ", new[] { "z", "uw" } },
            { "て", new[] { "t", "eh" } },
            { "で", new[] { "d", "eh" } },
            { "と", new[] { "t", "ow" } },
            { "ど", new[] { "d", "ow" } },
            { "な", new[] { "n", "aa" } },
            { "に", new[] { "n", "iy" } },
            { "ぬ", new[] { "n", "uw" } },
            { "ね", new[] { "n", "eh" } },
            { "の", new[] { "n", "ow" } },
            { "は", new[] { "hh", "aa" } },
            { "ば", new[] { "b", "aa" } },
            { "ぱ", new[] { "p", "aa" } },
            { "ひ", new[] { "hh", "iy" } },
            { "び", new[] { "b", "iy" } },
            { "ぴ", new[] { "p", "iy" } },
            { "ふ", new[] { "f", "uw" } },
            { "ぶ", new[] { "b", "uw" } },
            { "ぷ", new[] { "p", "uw" } },
            { "へ", new[] { "hh", "eh" } },
            { "べ", new[] { "b", "eh" } },
            { "ぺ", new[] { "p", "eh" } },
            { "ほ", new[] { "hh", "ow" } },
            { "ぼ", new[] { "b", "ow" } },
            { "ぽ", new[] { "p", "ow" } },
            { "ま", new[] { "m", "aa" } },
            { "み", new[] { "m", "iy" } },
            { "む", new[] { "m", "uw" } },
            { "め", new[] { "m", "eh" } },
            { "も", new[] { "m", "ow" } },
            { "や", new[] { "y", "aa" } },
            { "ゆ", new[] { "y", "uw" } },
            { "よ", new[] { "y", "ow" } },
            { "ら", new[] { "r", "aa" } },
            { "り", new[] { "r", "iy" } },
            { "る", new[] { "r", "uw" } },
            { "れ", new[] { "r", "eh" } },
            { "ろ", new[] { "r", "ow" } },
            { "ゎ", new[] { "w", "aa" } },
            { "わ", new[] { "w", "aa" } },
            { "ゐ", new[] { "w", "iy" } },
            { "ゑ", new[] { "w", "eh" } },
            { "を", new[] { "w", "ow" } },
            { "ゔ", new[] { "v", "uw" } },
            { "ゕ", new[] { "k", "aa" } },
            { "ゖ", new[] { "k", "eh" } },
            { "いぇ", new[] { "y", "eh" } },
            { "うぃ", new[] { "w", "iy" } },
            { "うぇ", new[] { "w", "eh" } },
            { "うぉ", new[] { "w", "ow" } },
            { "きゃ", new[] { "k", "y", "aa" } },
            { "きゅ", new[] { "k", "y", "uw" } },
            { "きょ", new[] { "k", "y", "ow" } },
            { "ぎゃ", new[] { "g", "iy", "y", "aa" } },
            { "ぎゅ", new[] { "g", "iy", "y", "uw" } },
            { "ぎょ", new[] { "g", "iy", "y", "ow" } },
            { "くぁ", new[] { "k", "w", "aa" } },
            { "くぃ", new[] { "k", "w", "iy" } },
            { "くぇ", new[] { "k", "w", "eh" } },
            { "くぉ", new[] { "k", "w", "ow" } },
            { "くゅ", new[] { "k", "y", "uw" } },
            { "ぐぁ", new[] { "g", "w", "aa" } },
            { "ぐぃ", new[] { "g", "w", "iy" } },
            { "ぐぇ", new[] { "g", "w", "eh" } },
            { "ぐぉ", new[] { "g", "w", "ow" } },
            { "ぐゅ", new[] { "g", "y", "uw" } },
            { "しぇ", new[] { "sh", "eh" } },
            { "しゃ", new[] { "sh", "aa" } },
            { "しゅ", new[] { "sh", "uw" } },
            { "しょ", new[] { "sh", "ow" } },
            { "じぇ", new[] { "jh", "eh" } },
            { "じゃ", new[] { "jh", "aa" } },
            { "じゅ", new[] { "jh", "uw" } },
            { "じょ", new[] { "jh", "ow" } },
            { "すぃ", new[] { "s", "iy" } },
            { "すゅ", new[] { "s", "y", "uw" } },
            { "ずぃ", new[] { "z", "iy" } },
            { "ずゅ", new[] { "z", "y", "uw" } },
            { "ちぇ", new[] { "ch", "eh" } },
            { "ちゃ", new[] { "ch", "aa" } },
            { "ちゅ", new[] { "ch", "uw" } },
            { "ちょ", new[] { "ch", "ow" } },
            { "つぁ", new[] { "t", "s", "aa" } },
            { "つぃ", new[] { "t", "s", "iy" } },
            { "つぇ", new[] { "t", "s", "eh" } },
            { "つぉ", new[] { "t", "s", "ow" } },
            { "てぃ", new[] { "t", "iy" } },
            { "てゅ", new[] { "t", "y", "uw" } },
            { "でぃ", new[] { "d", "iy" } },
            { "でゅ", new[] { "d", "y", "uw" } },
            { "とぁ", new[] { "t", "w", "aa" } },
            { "とぃ", new[] { "t", "w", "iy" } },
            { "とぅ", new[] { "t", "uw" } },
            { "とぇ", new[] { "t", "w", "eh" } },
            { "とぉ", new[] { "t", "w", "ow" } },
            { "どぁ", new[] { "d", "w", "aa" } },
            { "どぃ", new[] { "d", "w", "iy" } },
            { "どぅ", new[] { "d", "uw" } },
            { "どぇ", new[] { "d", "w", "eh" } },
            { "どぉ", new[] { "d", "w", "ow" } },
            { "にゃ", new[] { "n", "iy", "y", "aa" } },
            { "にゅ", new[] { "n", "iy", "y", "uw" } },
            { "にょ", new[] { "n", "iy", "y", "ow" } },
            { "ひゃ", new[] { "hh", "iy", "y", "aa" } },
            { "ひゅ", new[] { "hh", "iy", "y", "uw" } },
            { "ひょ", new[] { "hh", "iy", "y", "ow" } },
            { "びゃ", new[] { "b", "y", "aa" } },
            { "びゅ", new[] { "b", "y", "uw" } },
            { "びょ", new[] { "b", "y", "ow" } },
            { "ぴゃ", new[] { "p", "iy", "y", "aa" } },
            { "ぴゅ", new[] { "p", "iy", "y", "uw" } },
            { "ぴょ", new[] { "p", "iy", "y", "ow" } },
            { "ふぁ", new[] { "f", "aa" } },
            { "ふぃ", new[] { "f", "iy" } },
            { "ふぇ", new[] { "f", "eh" } },
            { "ふぉ", new[] { "f", "ow" } },
            { "ふゅ", new[] { "f", "y", "uw" } },
            { "みゃ", new[] { "m", "y", "aa" } },
            { "みゅ", new[] { "m", "y", "uw" } },
            { "みょ", new[] { "m", "y", "ow" } },
            { "りゃ", new[] { "r", "iy", "y", "aa" } },
            { "りゅ", new[] { "r", "iy", "y", "uw" } },
            { "りょ", new[] { "r", "iy", "y", "ow" } },
            { "ゔぁ", new[] { "v", "aa" } },
            { "ゔぃ", new[] { "v", "iy" } },
            { "ゔぇ", new[] { "v", "eh" } },
            { "ゔぉ", new[] { "v", "ow" } },
            { "ゔゃ", new[] { "v", "y", "aa" } },
            { "ゔゅ", new[] { "v", "y", "uw" } },
            { "ゔょ", new[] { "v", "y", "ow" } },
            };
    }
}
